export const categoryMap = {
  expense: [
    {
      key: 'food',
      label: '식비',
      icon: 'fa-solid fa-utensils',
      iconClass: 'text-amber-500',
      activeClass: 'bg-amber-50 text-amber-600 ring-amber-200',
    },
    {
      key: 'transport',
      label: '교통',
      icon: 'fa-solid fa-bus',
      iconClass: 'text-sky-500',
      activeClass: 'bg-sky-50 text-sky-600 ring-sky-200',
    },
    {
      key: 'utilities',
      label: '공과금',
      icon: 'fa-solid fa-file-invoice-dollar',
      iconClass: 'text-slate-500',
      activeClass: 'bg-slate-100 text-slate-700 ring-slate-200',
    },
    {
      key: 'medical',
      label: '의료비',
      icon: 'fa-solid fa-pills',
      iconClass: 'text-rose-500',
      activeClass: 'bg-rose-50 text-rose-600 ring-rose-200',
    },
    {
      key: 'hobby',
      label: '취미/여가',
      icon: 'fa-solid fa-gamepad',
      iconClass: 'text-fuchsia-500',
      activeClass: 'bg-fuchsia-50 text-fuchsia-600 ring-fuchsia-200',
    },
    {
      key: 'essentials',
      label: '생필품',
      icon: 'fa-solid fa-cart-shopping',
      iconClass: 'text-zinc-500',
      activeClass: 'bg-zinc-100 text-zinc-700 ring-zinc-200',
    },
    {
      key: 'education',
      label: '교육',
      icon: 'fa-solid fa-book-open',
      iconClass: 'text-indigo-500',
      activeClass: 'bg-indigo-50 text-indigo-600 ring-indigo-200',
    },
    {
      key: 'subscription',
      label: '구독료',
      icon: 'fa-solid fa-credit-card',
      iconClass: 'text-violet-500',
      activeClass: 'bg-violet-50 text-violet-600 ring-violet-200',
    },
    {
      key: 'mobile',
      label: '통신비',
      icon: 'fa-solid fa-mobile-screen-button',
      iconClass: 'text-emerald-500',
      activeClass: 'bg-emerald-50 text-emerald-600 ring-emerald-200',
    },
    {
      key: 'beauty',
      label: '미용',
      icon: 'fa-solid fa-scissors',
      iconClass: 'text-pink-500',
      activeClass: 'bg-pink-50 text-pink-600 ring-pink-200',
    },
    {
      key: 'cafe',
      label: '카페/간식',
      icon: 'fa-solid fa-mug-hot',
      iconClass: 'text-orange-500',
      activeClass: 'bg-orange-50 text-orange-600 ring-orange-200',
    },
    {
      key: 'gift',
      label: '경조사/선물',
      icon: 'fa-solid fa-gift',
      iconClass: 'text-red-500',
      activeClass: 'bg-red-50 text-red-600 ring-red-200',
    },
    {
      key: 'travel',
      label: '여행',
      icon: 'fa-solid fa-plane-departure',
      iconClass: 'text-cyan-500',
      activeClass: 'bg-cyan-50 text-cyan-600 ring-cyan-200',
    },
    {
      key: 'clothes',
      label: '의류',
      icon: 'fa-solid fa-shirt',
      iconClass: 'text-blue-500',
      activeClass: 'bg-blue-50 text-blue-600 ring-blue-200',
    },
    {
      key: 'childcare',
      label: '육아',
      icon: 'fa-solid fa-baby',
      iconClass: 'text-yellow-500',
      activeClass: 'bg-yellow-50 text-yellow-700 ring-yellow-200',
    },
    {
      key: 'etc-expense',
      label: '기타',
      icon: 'fa-solid fa-ellipsis',
      iconClass: 'text-slate-500',
      activeClass: 'bg-slate-100 text-slate-700 ring-slate-300',
    },
  ],
  income: [
    {
      key: 'salary',
      label: '월급',
      icon: 'fa-solid fa-money-bill-wave',
      iconClass: 'text-emerald-500',
      activeClass: 'bg-emerald-50 text-emerald-600 ring-emerald-200',
    },
    {
      key: 'side-income',
      label: '부수입',
      icon: 'fa-solid fa-sack-dollar',
      iconClass: 'text-amber-500',
      activeClass: 'bg-amber-50 text-amber-600 ring-amber-200',
    },
    {
      key: 'allowance',
      label: '용돈',
      icon: 'fa-solid fa-piggy-bank',
      iconClass: 'text-pink-500',
      activeClass: 'bg-pink-50 text-pink-600 ring-pink-200',
    },
    {
      key: 'bonus',
      label: '보너스',
      icon: 'fa-solid fa-gift',
      iconClass: 'text-rose-500',
      activeClass: 'bg-rose-50 text-rose-600 ring-rose-200',
    },
    {
      key: 'etc-income',
      label: '기타',
      icon: 'fa-solid fa-ellipsis',
      iconClass: 'text-slate-500',
      activeClass: 'bg-slate-100 text-slate-700 ring-slate-300',
    },
  ],
};
